### ISSUE TITLE
Problems with compatability for Mac Safari, Chrome and Firefox

### ISSUE THREAD

**Issue by applemad** [mjackson/shadowbox#5] opened 2010-03-25 16:25 UTC
Hi Michael, I've posted on your own forums but they don't seem to have been read recently so thought I would try my luck here.

I've just purchased a commercial license from you in the last few days, however I'm having a problem where the latest 3.0.3 version isn't working properly in the Mac versions of the popular browsers, Safari being the worst but iframe sizes aren't being correctly set for Chrome or Firfox either.

I have done a short video for you to see the issue at the following web URL, and if you have mac machines then you can also access the pages in question at the second URL.

Thanks for your time

Craig Price

Video:
http://www.busybeeschildcare.co.uk/shadvid

Live URL:
http://www.busybeeschildcare.co.uk/nursery/burntwood

**Comment by mjackson** [comment] 2010-03-29 16:17
I'm unable to reproduce this issue on Safari 4.0.4 running on Snow Leopard. Also, from the video you provided it looks like you're using a modification of the default skin, which I can't support. Closing this as a wontfix.

**Closed as completed by mjackson** 2010-03-29 16:17 UTC
